<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AsyncRequestReplyPackageVersion Condition="'$(AsyncRequestReplyPackageVersion)' == ''">0.2.0</AsyncRequestReplyPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AsyncRequestReply" Version="$(AsyncRequestReplyPackageVersion)" />
  </ItemGroup>

</Project>
