name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_please:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          release-type: simple

  publish:
    needs: release_please
    if: ${{ needs.release_please.outputs.release_created == 'true' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/release.yml
